image: Visual Studio 2019

branches:
  only:
    - develop
    - master
    - feature/*

skip_tags: true

environment:
  JAVA_HOME: C:/Program Files/Java/jdk11
  
  sonar_login:
    secure: 6qD93a8X/HlviVML1h7oaD5Z57iWiGc6BLkgizomSUHAgcNeC6eQoY8sprEtlHtN
  
  CODECOV_TOKEN:
    secure: qpg2oUby8/m76bjOwVR+hoiGl5/k2CzSDtXnXoog0eZvvgC8k34Yj+IAUedg0yOM
  
build: off
test: off

before_build:
  cmd: >-
    choco install gitversion.portable -y --version 4.0.0
    
    gitversion /l console /output buildserver /updateAssemblyInfo
    
    choco install codecov

    dotnet tool install --global dotnet-sonarscanner
    
    dotnet restore src

build_script:
  ps: >-
    if ("$env:APPVEYOR_PULL_REQUEST_NUMBER" -eq "")
    {
      dotnet sonarscanner begin /k:"adz21c_Periturf.Web" /o:"adz21c-github" /v:"$env:GitVersion_FullSemVer" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_login" /d:sonar.branch.name="$env:APPVEYOR_REPO_BRANCH" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
    }
    else
    {
      dotnet sonarscanner begin /k:"adz21c_Periturf.Web" /o:"adz21c-github" /v:"$env:GitVersion_FullSemVer" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_login" /d:sonar.pullrequest.key="$env:APPVEYOR_PULL_REQUEST_NUMBER" /d:sonar.pullrequest.branch="$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH" /d:sonar.pullrequest.base="$env:APPVEYOR_REPO_BRANCH" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" 
    }
    
    dotnet build src --no-restore -c Release
    
    dotnet test .\src\Periturf.Web.Tests --collect:"XPlat code coverage" --settings:.\src\CodeCoverage.runsettings

    dotnet test .\src\Periturf.Web.Tests.Integration

    dotnet sonarscanner end /d:sonar.login="$env:sonar_login"
    
    codecov -f "**/coverage.opencover.xml" -t "$env:CODECOV_TOKEN"
    
    dotnet pack src --no-restore --no-build --include-symbols -c Release -p:PackageVersion=$env:GitVersion_NuGetVersionV2

artifacts:
- path: '**\bin\Release\*.nupkg'
  name: NuGetPackage

deploy:
- provider: NuGet
  api_key:
    secure: vYMb0LiGindib+iR4OY1PVUDUTf9odWJ1ajb0GDnkb2SnfK+zG/H4KUQp9sN3+Ka
  skip_symbols: true
  artifact: NuGetPackage
  on:
    branch: /master|develop/
